// Generated by CoffeeScript 1.9.3
(function() {
  var result, som;

  som = (function(_this) {
    return function(a, b) {
      return a + b;
    };
  })(this);

  result = som(4, 7);

  if (result > 0) {
    console.log(result);
  }

}).call(this);

//# sourceMappingURL=DemoCS.js.map
